const KEY='sorveteria_caixa_v1';
const defaultProducts=[
 {id:1,name:'Sorvete por kg',category:'Sorvetes',price:69.90,unit:'kg',emoji:'🍨'},
 {id:2,name:'Picolé de fruta',category:'Picolés',price:5.00,unit:'un',emoji:'🍧'},
 {id:3,name:'Picolé cremoso',category:'Picolés',price:7.00,unit:'un',emoji:'🍦'},
 {id:4,name:'Açaí 300ml',category:'Açaí',price:15.00,unit:'un',emoji:'🫐'},
 {id:5,name:'Açaí 500ml',category:'Açaí',price:20.00,unit:'un',emoji:'🫐'},
 {id:6,name:'Hot dog',category:'Lanches',price:12.00,unit:'un',emoji:'🌭'},
 {id:7,name:'X-Salada',category:'Lanches',price:18.00,unit:'un',emoji:'🍔'},
 {id:8,name:'Batata frita',category:'Lanches',price:14.00,unit:'un',emoji:'🍟'},
 {id:9,name:'Refrigerante lata',category:'Bebidas',price:6.00,unit:'un',emoji:'🥤'},
 {id:10,name:'Água',category:'Bebidas',price:4.00,unit:'un',emoji:'💧'},
 {id:11,name:'Calda extra',category:'Adicionais',price:2.50,unit:'un',emoji:'🍫'},
 {id:12,name:'Granulado',category:'Adicionais',price:2.00,unit:'un',emoji:'✨'}
];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{products:defaultProducts,sales:[],nextOrder:1};
let cart=[],category='Todos',payment=null,weight=0,reader=null;
const $=id=>document.getElementById(id);
const brl=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function renderCategories(){const cats=['Todos',...new Set(state.products.map(p=>p.category))];$('categories').innerHTML=cats.map(c=>`<button class="chip ${c===category?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()})}
function renderProducts(){const q=$('search').value.toLowerCase();let ps=state.products.filter(p=>(category==='Todos'||p.category===category)&&p.name.toLowerCase().includes(q));$('products').innerHTML=ps.map(p=>`<button class="product" data-product="${p.id}"><div class="emoji">${p.emoji}</div><div class="name">${p.name}</div><div class="meta">${p.unit==='kg'?'por kg':'unidade'}</div><div class="price">${brl(p.price)}${p.unit==='kg'?'/kg':''}</div></button>`).join('');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addProduct(+b.dataset.product))}
function addProduct(id,qty=1){const p=state.products.find(x=>x.id===id);if(!p)return;let item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({...p,qty});renderCart()}
function addWeight(){let p=state.products.find(x=>x.unit==='kg');if(!p){toast('Cadastre um produto vendido por kg.');return}if(weight<=0){toast('Informe/conecte o peso primeiro.');return}cart.push({...p,id:`w-${Date.now()}`,name:`${p.name} (${weight.toFixed(3)} kg)`,qty:weight,price:p.price,weightItem:true});weight=0;updateWeight();renderCart();toast('Peso adicionado ao pedido.')}
function renderCart(){if(!cart.length){$('cart').innerHTML='<div class="empty">Nenhum item no pedido.<br>Escolha um produto ao lado.</div>'}else{$('cart').innerHTML=cart.map((i,idx)=>`<div class="cart-item"><div><div class="cart-name">${i.name}</div><div class="cart-sub">${i.weightItem?i.qty.toFixed(3)+' kg × '+brl(i.price):brl(i.price)+' × '+i.qty}</div><button class="remove" data-remove="${idx}">Remover</button></div><div class="qty">${i.weightItem?'':`<button data-dec="${idx}">−</button><span>${i.qty}</span><button data-inc="${idx}">+</button>`}</div></div>`).join('');document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{cart[+b.dataset.inc].qty++;renderCart()});document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const i=+b.dataset.dec;cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);renderCart()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()})}const total=cart.reduce((s,i)=>s+i.price*i.qty,0);$('subtotal').textContent=brl(total);$('total').textContent=brl(total);updateChange();}
function updateWeight(){$('weight').textContent=weight.toLocaleString('pt-BR',{minimumFractionDigits:3,maximumFractionDigits:3})}
function updateChange(){const total=cart.reduce((s,i)=>s+i.price*i.qty,0),r=parseFloat($('cashReceived').value||0);$('change').textContent=brl(Math.max(0,r-total))}
function render(){renderCategories();renderProducts();renderCart();$('orderNumber').textContent='Pedido #'+String(state.nextOrder).padStart(3,'0')}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function productsModal(editId){const editing=editId?state.products.find(p=>p.id===editId):null;openModal('Cadastro de produtos',`<div class="form"><div><label>Nome</label><input id="pn" placeholder="Ex.: Milk-shake" value="${editing?editing.name:''}"></div><div><label>Categoria</label><input id="pc" placeholder="Ex.: Bebidas" value="${editing?editing.category:''}"></div><div><label>Preço</label><input id="pp" type="number" step="0.01" placeholder="0,00" value="${editing?editing.price:''}"></div><div><label>Unidade</label><select id="pu"><option value="un" ${editing&&editing.unit==='un'?'selected':''}>Unidade</option><option value="kg" ${editing&&editing.unit==='kg'?'selected':''}>Kg</option></select></div><div><label>Emoji</label><input id="pe" value="${editing?editing.emoji:'🍦'}"></div><div style="display:flex;align-items:end"><button id="addP">${editing?'Salvar alterações':'Adicionar produto'}</button></div></div><table class="table"><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th></th></tr></thead><tbody>${state.products.map(p=>`<tr><td>${p.emoji} ${p.name}</td><td>${p.category}</td><td>${brl(p.price)}${p.unit==='kg'?'/kg':''}</td><td style="display:flex;gap:6px"><button class="remove" data-edit-product="${p.id}" style="color:var(--primary)">Editar</button><button class="remove" data-del-product="${p.id}">Excluir</button></td></tr>`).join('')}</tbody></table><div style="margin-top:18px;border-top:1px solid var(--line);padding-top:14px;display:flex;gap:8px;flex-wrap:wrap"><button class="secondary" id="exportBackup">💾 Exportar backup</button><label class="secondary" style="display:inline-flex;align-items:center;cursor:pointer">📂 Importar backup<input type="file" id="importBackup" accept="application/json" style="display:none"></label></div>`);$('addP').onclick=()=>{const name=$('pn').value.trim(),price=+$('pp').value;if(!name||!price){toast('Preencha nome e preço.');return}if(editing){editing.name=name;editing.category=$('pc').value.trim()||'Outros';editing.price=price;editing.unit=$('pu').value;editing.emoji=$('pe').value||'🍦'}else{state.products.push({id:Date.now(),name,category:$('pc').value.trim()||'Outros',price,unit:$('pu').value,emoji:$('pe').value||'🍦'})}save();productsModal();render()};document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>productsModal(+b.dataset.editProduct));document.querySelectorAll('[data-del-product]').forEach(b=>b.onclick=()=>{if(!confirm('Excluir este produto?'))return;state.products=state.products.filter(p=>p.id!==+b.dataset.delProduct);save();productsModal();render()});$('exportBackup').onclick=exportBackup;$('importBackup').onchange=importBackup}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-sorveteria-${new Date().toISOString().slice(0,10)}.json`;a.click();toast('Backup exportado.')}
function importBackup(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.products||!data.sales)throw 0;if(!confirm('Isso vai substituir os produtos e vendas atuais. Continuar?'))return;state=data;save();productsModal();render();toast('Backup importado.')}catch(err){toast('Arquivo de backup inválido.')}};r.readAsText(file)}
function localDay(d){const dt=new Date(d);return`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`}
function reportsModal(){const sales=state.sales;const total=sales.reduce((s,x)=>s+x.total,0);const todayKey=localDay(new Date());const todaySales=sales.filter(x=>localDay(x.date)===todayKey);const todayTotal=todaySales.reduce((s,x)=>s+x.total,0);const byPay={};sales.forEach(x=>byPay[x.payment]=(byPay[x.payment]||0)+x.total);const rows=Object.entries(byPay).map(([k,v])=>`<tr><td>${k}</td><td>${brl(v)}</td></tr>`).join('');openModal('Relatórios',`<div class="stats"><div class="stat"><small>Vendas hoje</small><strong>${brl(todayTotal)}</strong></div><div class="stat"><small>Pedidos hoje</small><strong>${todaySales.length}</strong></div><div class="stat"><small>Total histórico</small><strong>${brl(total)}</strong></div></div><h3>Por forma de pagamento</h3><table class="table"><tbody>${rows||'<tr><td>Nenhuma venda ainda.</td></tr>'}</tbody></table><div style="display:flex;justify-content:space-between;align-items:center;margin-top:15px"><h3 style="margin:0">Últimas vendas</h3><button class="secondary" id="exportCsv">⬇️ Exportar CSV</button></div><table class="table"><thead><tr><th>Pedido</th><th>Data</th><th>Pagamento</th><th>Total</th></tr></thead><tbody>${sales.slice().reverse().slice(0,30).map(x=>`<tr><td>#${String(x.order).padStart(3,'0')}</td><td>${new Date(x.date).toLocaleString('pt-BR')}</td><td>${x.payment}</td><td>${brl(x.total)}</td></tr>`).join('')||'<tr><td colspan="4">Nenhuma venda.</td></tr>'}</tbody></table>`);$('exportCsv').onclick=exportSalesCsv}
function exportSalesCsv(){if(!state.sales.length){toast('Nenhuma venda para exportar.');return}const header='Pedido;Data;Pagamento;Total;Itens\n';const rows=state.sales.map(x=>{const itens=x.items.map(i=>`${i.name} x${i.qty}`).join(', ').replace(/;/g,',');return`${x.order};${new Date(x.date).toLocaleString('pt-BR')};${x.payment};${x.total.toFixed(2).replace('.',',')};"${itens}"`}).join('\n');const blob=new Blob(['\ufeff'+header+rows],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vendas-${new Date().toISOString().slice(0,10)}.csv`;a.click()}
function scaleModal(){openModal('Configuração da balança',`<p>Use uma balança USB/serial compatível com o navegador. No Chrome/Edge, o botão abaixo tenta abrir a porta. A balança deve enviar o peso em linhas de texto (por exemplo: <b>0.325</b>, <b>0,325 kg</b> ou <b>ST,GS, 0.325kg</b>).</p><button class="finish" id="scaleConnectModal">Conectar balança USB</button><p style="color:#777;font-size:12px;margin-top:10px">Se a sua balança usa protocolo específico, será necessário ajustar o leitor em app.js para o protocolo/modelo dela.</p>`);$('scaleConnectModal').onclick=connectScale}
async function connectScale(){if(!('serial' in navigator)){toast('Seu navegador não suporta Web Serial. Use Chrome ou Edge no computador.');return}try{const port=await navigator.serial.requestPort();await port.open({baudRate:9600});reader=port.readable.getReader();$('scaleStatus').textContent='Balança conectada';toast('Balança conectada.');readScale()}catch(e){toast('Não foi possível conectar: '+e.message)}}
async function readScale(){if(!reader)return;let buffer='';try{while(true){const {value,done}=await reader.read();if(done)break;buffer+=new TextDecoder().decode(value);const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines){const m=line.replace(',','.').match(/([0-9]+(?:\.[0-9]+)?)/);if(m){let v=parseFloat(m[1]);if(/kg/i.test(line)){}else if(v>10)v=v/1000;weight=v;updateWeight()}}}}catch(e){$('scaleStatus').textContent='Balança desconectada'}}
function finishSale(){if(!cart.length){toast('Adicione itens ao pedido.');return}if(!payment){toast('Escolha a forma de pagamento.');return}const total=cart.reduce((s,i)=>s+i.price*i.qty,0);if(payment==='Dinheiro'&&parseFloat($('cashReceived').value||0)<total){toast('Valor recebido é menor que o total.');return}const troco=payment==='Dinheiro'?Math.max(0,parseFloat($('cashReceived').value||0)-total):0;const sale={order:state.nextOrder,date:new Date().toISOString(),payment,total,troco,items:cart.map(i=>({name:i.name,qty:i.qty,price:i.price}))};state.sales.push(sale);state.nextOrder++;save();cart=[];payment=null;$('cashReceived').value='';$('cashChange').classList.add('hidden');document.querySelectorAll('[data-payment]').forEach(b=>b.classList.remove('selected'));render();toast(`Venda #${String(sale.order).padStart(3,'0')} concluída${troco?` • Troco ${brl(troco)}`:''}`);receiptModal(sale)}
function receiptModal(sale){const itemsHtml=sale.items.map(i=>`<tr><td>${i.name}</td><td style="text-align:right">${typeof i.qty==='number'&&i.qty%1!==0?i.qty.toFixed(3):i.qty}</td><td style="text-align:right">${brl(i.price*i.qty)}</td></tr>`).join('');openModal('Venda concluída',`<div id="receiptPrint"><div style="text-align:center;margin-bottom:10px"><strong style="font-size:18px">🍦 Sorveteria</strong><div style="color:var(--muted);font-size:13px">Pedido #${String(sale.order).padStart(3,'0')} • ${new Date(sale.date).toLocaleString('pt-BR')}</div></div><table class="table"><thead><tr><th>Item</th><th style="text-align:right">Qtd</th><th style="text-align:right">Total</th></tr></thead><tbody>${itemsHtml}</tbody></table><div class="totals"><div class="total"><span>Total</span><strong>${brl(sale.total)}</strong></div><div><span>Pagamento</span><strong>${sale.payment}</strong></div>${sale.troco?`<div><span>Troco</span><strong>${brl(sale.troco)}</strong></div>`:''}</div></div><button class="finish" id="printReceipt" style="margin-top:14px">🖨️ Imprimir recibo</button>`);$('printReceipt').onclick=()=>window.print()}
$('search').addEventListener('input',renderProducts);$('clearCart').onclick=()=>{cart=[];payment=null;render();document.querySelectorAll('[data-payment]').forEach(b=>b.classList.remove('selected'))};$('useWeight').onclick=addWeight;$('connectScale').onclick=connectScale;$('cashReceived').addEventListener('input',updateChange);$('finishSale').onclick=finishSale;$('openProducts').onclick=productsModal;$('openReports').onclick=reportsModal;$('openSettings').onclick=scaleModal;$('closeModal').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});document.querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>{payment=b.dataset.payment;document.querySelectorAll('[data-payment]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('cashChange').classList.toggle('hidden',payment!=='Dinheiro')});render();
