const KEY='sorveteria_caixa_v1';
const defaultProducts=[
 {id:1,num:1,name:'Sorvete por kg',category:'Sorvetes',price:69.90,unit:'kg'},
 {id:2,num:2,name:'Picolé de fruta',category:'Picolés',price:5.00,unit:'un'},
 {id:3,num:3,name:'Picolé cremoso',category:'Picolés',price:7.00,unit:'un'},
 {id:4,num:4,name:'Açaí 300ml',category:'Açaí',price:15.00,unit:'un'},
 {id:5,num:5,name:'Açaí 500ml',category:'Açaí',price:20.00,unit:'un'},
 {id:6,num:6,name:'Hot dog',category:'Lanches',price:12.00,unit:'un'},
 {id:7,num:7,name:'X-Salada',category:'Lanches',price:18.00,unit:'un'},
 {id:8,num:8,name:'Batata frita',category:'Lanches',price:14.00,unit:'un'},
 {id:9,num:9,name:'Refrigerante lata',category:'Bebidas',price:6.00,unit:'un'},
 {id:10,num:10,name:'Água',category:'Bebidas',price:4.00,unit:'un'},
 {id:11,num:11,name:'Calda extra',category:'Adicionais',price:2.50,unit:'un'},
 {id:12,num:12,name:'Granulado',category:'Adicionais',price:2.00,unit:'un'}
];
const defaultUsers=[
 {id:'admin-fixo',name:'Administrador',username:'Admin',password:'3012Jaque@',role:'admin',fixed:true},
 {id:'caixa-fixo',name:'Caixa SF',username:'CaixaSF',password:'3030SF@',role:'operador',fixed:true}
];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{products:defaultProducts,sales:[],nextOrder:1,users:defaultUsers,nextProductNum:13};
if(!state.users||!state.users.length)state.users=defaultUsers;
defaultUsers.forEach(du=>{if(!state.users.some(u=>u.username.toLowerCase()===du.username.toLowerCase()))state.users.push(du)});
if(!state.nextProductNum)state.nextProductNum=Math.max(13,...state.products.map(p=>p.num||0))+1;
state.products.forEach((p,idx)=>{if(!p.num)p.num=idx+1});
let cart=[],category='Todos',payment=null,weight=0,reader=null,currentUser=null,discount=0,splitMode=false,splits=[];
const SESSION_KEY='sorveteria_session';
const $=id=>document.getElementById(id);
const brl=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function getSubtotal(){return cart.reduce((s,i)=>s+i.price*i.qty,0)}
function getTotal(){return Math.max(0,getSubtotal()-(discount||0))}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg){$('toast').textContent=msg;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2200)}
function renderCategories(){const cats=['Todos',...new Set(state.products.map(p=>p.category))];$('categories').innerHTML=cats.map(c=>`<button class="chip ${c===category?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()})}
function renderProducts(){const q=$('search').value.toLowerCase().trim();let ps=state.products.filter(p=>(category==='Todos'||p.category===category)&&(p.name.toLowerCase().includes(q)||String(p.num).includes(q)||String(p.num).padStart(2,'0').includes(q)));$('products').innerHTML=ps.map(p=>`<button class="product" data-product="${p.id}"><div class="num">Nº ${String(p.num).padStart(2,'0')}</div><div class="name">${p.name}</div><div class="meta">${p.unit==='kg'?'por kg':'unidade'}</div><div class="price">${brl(p.price)}${p.unit==='kg'?'/kg':''}</div></button>`).join('');document.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>addProduct(+b.dataset.product))}
function addProduct(id,qty=1){const p=state.products.find(x=>x.id===id);if(!p)return;let item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({...p,qty});renderCart()}
function addWeight(){let p=state.products.find(x=>x.unit==='kg');if(!p){toast('Cadastre um produto vendido por kg.');return}if(weight<=0){toast('Informe/conecte o peso primeiro.');return}cart.push({...p,id:`w-${Date.now()}`,name:`${p.name} (${weight.toFixed(3)} kg)`,qty:weight,price:p.price,weightItem:true});weight=0;updateWeight();renderCart();toast('Peso adicionado ao pedido.')}
function renderCart(){if(!cart.length){$('cart').innerHTML='<div class="empty">Nenhum item no pedido.<br>Escolha um produto ao lado.</div>'}else{$('cart').innerHTML=cart.map((i,idx)=>`<div class="cart-item"><div><div class="cart-name">Nº ${String(i.num).padStart(2,'0')} · ${i.name}</div><div class="cart-sub">${i.weightItem?i.qty.toFixed(3)+' kg × '+brl(i.price):brl(i.price)+' × '+i.qty}</div><button class="remove" data-remove="${idx}">Remover</button></div><div class="qty">${i.weightItem?'':`<button data-dec="${idx}">−</button><span>${i.qty}</span><button data-inc="${idx}">+</button>`}</div></div>`).join('');document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>{cart[+b.dataset.inc].qty++;renderCart()});document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const i=+b.dataset.dec;cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);renderCart()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);renderCart()})}$('subtotal').textContent=brl(getSubtotal());$('total').textContent=brl(getTotal());updateChange();updateSplitRemaining();}
function updateWeight(){$('weight').textContent=weight.toLocaleString('pt-BR',{minimumFractionDigits:3,maximumFractionDigits:3})}
function updateChange(){const total=getTotal(),r=parseFloat($('cashReceived').value||0);$('change').textContent=brl(Math.max(0,r-total))}
function toggleSplit(){splitMode=!splitMode;$('singlePayment').classList.toggle('hidden',splitMode);$('splitPayment').classList.toggle('hidden',!splitMode);$('toggleSplit').textContent=splitMode?'Pagamento único':'Dividir pagamento';payment=null;document.querySelectorAll('[data-payment]').forEach(x=>x.classList.remove('selected'));$('cashChange').classList.add('hidden');if(!splitMode){splits=[]}renderSplitList()}
function addSplit(){const method=$('splitMethod').value,value=parseFloat($('splitValue').value||0);if(!value||value<=0){toast('Informe um valor válido.');return}splits.push({method,value});$('splitValue').value='';$('splitValue').focus();renderSplitList()}
function renderSplitList(){if(!$('splitList'))return;$('splitList').innerHTML=splits.map((s,idx)=>`<div class="split-item"><span>${s.method}</span><span>${brl(s.value)}</span><button class="remove" data-del-split="${idx}">Remover</button></div>`).join('')||'<div class="empty" style="padding:12px;font-size:12px">Nenhum valor adicionado ainda.</div>';document.querySelectorAll('[data-del-split]').forEach(b=>b.onclick=()=>{splits.splice(+b.dataset.delSplit,1);renderSplitList()});updateSplitRemaining()}
function updateSplitRemaining(){if(!$('splitRemaining'))return;const total=getTotal(),allocated=splits.reduce((s,x)=>s+x.value,0),remaining=total-allocated;let label,cls='';if(Math.abs(remaining)<0.01){label='Valores conferem com o total.';cls='ok'}else if(remaining>0){label=`Falta alocar: ${brl(remaining)}`}else{label=`Valor excede o total em ${brl(-remaining)}`;cls='over'}$('splitRemaining').textContent=label;$('splitRemaining').className='split-remaining'+(cls?' '+cls:'')}

function render(){renderCategories();renderProducts();renderCart();$('orderNumber').textContent='Pedido #'+String(state.nextOrder).padStart(3,'0')}
function openModal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}
function closeModal(){$('modal').classList.add('hidden')}
function productsModal(editId){const editing=editId?state.products.find(p=>p.id===editId):null;const isAdmin=currentUser.role==='admin';openModal('Cadastro de produtos',`<div class="form"><div><label>Nome</label><input id="pn" placeholder="Ex.: Milk-shake" value="${editing?editing.name:''}"></div><div><label>Categoria</label><input id="pc" placeholder="Ex.: Bebidas" value="${editing?editing.category:''}"></div><div><label>Preço</label><input id="pp" type="number" step="0.01" placeholder="0,00" value="${editing?editing.price:''}"></div><div><label>Unidade</label><select id="pu"><option value="un" ${editing&&editing.unit==='un'?'selected':''}>Unidade</option><option value="kg" ${editing&&editing.unit==='kg'?'selected':''}>Kg</option></select></div><div style="display:flex;align-items:end"><button id="addP">${editing?'Salvar alterações':'Adicionar produto'}</button></div></div><table class="table"><thead><tr><th>Nº</th><th>Produto</th><th>Categoria</th><th>Preço</th><th></th></tr></thead><tbody>${state.products.map(p=>`<tr><td>${String(p.num).padStart(2,'0')}</td><td>${p.name}</td><td>${p.category}</td><td>${brl(p.price)}${p.unit==='kg'?'/kg':''}</td><td style="display:flex;gap:6px"><button class="remove" data-edit-product="${p.id}" style="color:var(--primary)">Editar</button><button class="remove" data-del-product="${p.id}" ${!isAdmin?'disabled title="Apenas administradores podem excluir"':''}>Excluir</button></td></tr>`).join('')}</tbody></table><div style="margin-top:18px;border-top:1px solid var(--line);padding-top:14px;display:flex;gap:8px;flex-wrap:wrap"><button class="secondary" id="exportBackup">Exportar backup</button><label class="secondary" style="display:inline-flex;align-items:center;cursor:pointer">Importar backup<input type="file" id="importBackup" accept="application/json" style="display:none"></label></div>`);$('addP').onclick=()=>{const name=$('pn').value.trim(),price=+$('pp').value;if(!name||!price){toast('Preencha nome e preço.');return}if(editing){editing.name=name;editing.category=$('pc').value.trim()||'Outros';editing.price=price;editing.unit=$('pu').value}else{state.products.push({id:Date.now(),num:state.nextProductNum++,name,category:$('pc').value.trim()||'Outros',price,unit:$('pu').value})}save();productsModal();render()};document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>productsModal(+b.dataset.editProduct));document.querySelectorAll('[data-del-product]').forEach(b=>b.onclick=()=>{if(b.disabled)return;if(!confirm('Excluir este produto?'))return;state.products=state.products.filter(p=>p.id!==+b.dataset.delProduct);save();productsModal();render()});$('exportBackup').onclick=exportBackup;$('importBackup').onchange=importBackup}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-sorveteria-${new Date().toISOString().slice(0,10)}.json`;a.click();toast('Backup exportado.')}
function importBackup(e){const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data.products||!data.sales)throw 0;if(!data.users)data.users=state.users;if(!confirm('Isso vai substituir os produtos, vendas e usuários atuais. Continuar?'))return;state=data;save();productsModal();render();toast('Backup importado.')}catch(err){toast('Arquivo de backup inválido.')}};r.readAsText(file)}
function localDay(d){const dt=new Date(d);return`${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`}
function reportsModal(){const sales=state.sales;const total=sales.reduce((s,x)=>s+x.total,0);const totalDiscount=sales.reduce((s,x)=>s+(x.discount||0),0);const todayKey=localDay(new Date());const todaySales=sales.filter(x=>localDay(x.date)===todayKey);const todayTotal=todaySales.reduce((s,x)=>s+x.total,0);const byPay={};sales.forEach(x=>{if(x.payments&&x.payments.length){x.payments.forEach(p=>{byPay[p.method]=(byPay[p.method]||0)+p.value})}else{byPay[x.payment]=(byPay[x.payment]||0)+x.total}});const rows=Object.entries(byPay).map(([k,v])=>`<tr><td>${k}</td><td>${brl(v)}</td></tr>`).join('');openModal('Relatórios',`<div class="stats"><div class="stat"><small>Vendas hoje</small><strong>${brl(todayTotal)}</strong></div><div class="stat"><small>Pedidos hoje</small><strong>${todaySales.length}</strong></div><div class="stat"><small>Total histórico</small><strong>${brl(total)}</strong></div><div class="stat"><small>Descontos concedidos</small><strong>${brl(totalDiscount)}</strong></div></div><h3>Por forma de pagamento</h3><table class="table"><tbody>${rows||'<tr><td>Nenhuma venda ainda.</td></tr>'}</tbody></table><div style="display:flex;justify-content:space-between;align-items:center;margin-top:15px"><h3 style="margin:0">Últimas vendas</h3><button class="secondary" id="exportCsv">Exportar CSV</button></div><table class="table"><thead><tr><th>Pedido</th><th>Data</th><th>Operador</th><th>Pagamento</th><th>Total</th></tr></thead><tbody>${sales.slice().reverse().slice(0,30).map(x=>`<tr><td>#${String(x.order).padStart(3,'0')}</td><td>${new Date(x.date).toLocaleString('pt-BR')}</td><td>${x.user||'—'}</td><td>${x.payment}</td><td>${brl(x.total)}</td></tr>`).join('')||'<tr><td colspan="5">Nenhuma venda.</td></tr>'}</tbody></table>`);$('exportCsv').onclick=exportSalesCsv}
function exportSalesCsv(){if(!state.sales.length){toast('Nenhuma venda para exportar.');return}const header='Pedido;Data;Operador;Pagamento;Subtotal;Desconto;Total;Itens\n';const rows=state.sales.map(x=>{const itens=x.items.map(i=>`${i.num?'Nº'+String(i.num).padStart(2,'0')+' ':''}${i.name} x${i.qty}`).join(', ').replace(/;/g,',');const subtotal=(x.subtotal!=null?x.subtotal:x.total);return`${x.order};${new Date(x.date).toLocaleString('pt-BR')};${x.user||''};${x.payment};${subtotal.toFixed(2).replace('.',',')};${(x.discount||0).toFixed(2).replace('.',',')};${x.total.toFixed(2).replace('.',',')};"${itens}"`}).join('\n');const blob=new Blob(['\ufeff'+header+rows],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vendas-${new Date().toISOString().slice(0,10)}.csv`;a.click()}
function scaleModal(){openModal('Configuração da balança',`<p>Use uma balança USB/serial compatível com o navegador. No Chrome/Edge, o botão abaixo tenta abrir a porta. A balança deve enviar o peso em linhas de texto (por exemplo: <b>0.325</b>, <b>0,325 kg</b> ou <b>ST,GS, 0.325kg</b>).</p><button class="finish" id="scaleConnectModal">Conectar balança USB</button><p style="color:#777;font-size:12px;margin-top:10px">Se a sua balança usa protocolo específico, será necessário ajustar o leitor em app.js para o protocolo/modelo dela.</p>`);$('scaleConnectModal').onclick=connectScale}
async function connectScale(){if(!('serial' in navigator)){toast('Seu navegador não suporta Web Serial. Use Chrome ou Edge no computador.');return}try{const port=await navigator.serial.requestPort();await port.open({baudRate:9600});reader=port.readable.getReader();$('scaleStatus').textContent='Balança conectada';toast('Balança conectada.');readScale()}catch(e){toast('Não foi possível conectar: '+e.message)}}
async function readScale(){if(!reader)return;let buffer='';try{while(true){const {value,done}=await reader.read();if(done)break;buffer+=new TextDecoder().decode(value);const lines=buffer.split(/\r?\n/);buffer=lines.pop()||'';for(const line of lines){const m=line.replace(',','.').match(/([0-9]+(?:\.[0-9]+)?)/);if(m){let v=parseFloat(m[1]);if(/kg/i.test(line)){}else if(v>10)v=v/1000;weight=v;updateWeight()}}}}catch(e){$('scaleStatus').textContent='Balança desconectada'}}
function finishSale(){if(!cart.length){toast('Adicione itens ao pedido.');return}const total=getTotal();let paymentLabel,paymentsDetail=null,troco=0;if(splitMode){if(!splits.length){toast('Adicione ao menos uma forma de pagamento.');return}const allocated=splits.reduce((s,x)=>s+x.value,0);if(Math.abs(allocated-total)>0.01){toast(allocated<total?'Falta alocar o valor restante.':'O valor dividido excede o total.');return}paymentLabel='Dividido ('+splits.map(s=>`${s.method} ${brl(s.value)}`).join(' + ')+')';paymentsDetail=splits.slice()}else{if(!payment){toast('Escolha a forma de pagamento.');return}if(payment==='Dinheiro'&&parseFloat($('cashReceived').value||0)<total){toast('Valor recebido é menor que o total.');return}troco=payment==='Dinheiro'?Math.max(0,parseFloat($('cashReceived').value||0)-total):0;paymentLabel=payment}const sale={order:state.nextOrder,date:new Date().toISOString(),payment:paymentLabel,payments:paymentsDetail,subtotal:getSubtotal(),discount:discount||0,total,troco,user:currentUser?currentUser.name:'—',items:cart.map(i=>({num:i.num,name:i.name,qty:i.qty,price:i.price}))};state.sales.push(sale);state.nextOrder++;save();cart=[];payment=null;discount=0;splits=[];splitMode=false;$('discountInput').value='';$('cashReceived').value='';$('cashChange').classList.add('hidden');document.querySelectorAll('[data-payment]').forEach(b=>b.classList.remove('selected'));$('singlePayment').classList.remove('hidden');$('splitPayment').classList.add('hidden');$('toggleSplit').textContent='Dividir pagamento';renderSplitList();render();toast(`Venda #${String(sale.order).padStart(3,'0')} concluída${troco?` • Troco ${brl(troco)}`:''}`);receiptModal(sale)}
function receiptModal(sale){const itemsHtml=sale.items.map(i=>`<tr><td>${i.num?'Nº '+String(i.num).padStart(2,'0')+' · ':''}${i.name}</td><td style="text-align:right">${typeof i.qty==='number'&&i.qty%1!==0?i.qty.toFixed(3):i.qty}</td><td style="text-align:right">${brl(i.price*i.qty)}</td></tr>`).join('');const paymentRows=sale.payments&&sale.payments.length?sale.payments.map(p=>`<div><span>${p.method}</span><strong>${brl(p.value)}</strong></div>`).join(''):`<div><span>Pagamento</span><strong>${sale.payment}</strong></div>`;openModal('Venda concluída',`<div id="receiptPrint"><div style="text-align:center;margin-bottom:10px"><img src="logo.png" alt="S&F" style="width:60px;height:60px;border-radius:50%"><div><strong style="font-size:18px">S&F</strong></div><div style="color:var(--muted);font-size:13px">Pedido #${String(sale.order).padStart(3,'0')} • ${new Date(sale.date).toLocaleString('pt-BR')}</div></div><table class="table"><thead><tr><th>Item</th><th style="text-align:right">Qtd</th><th style="text-align:right">Total</th></tr></thead><tbody>${itemsHtml}</tbody></table><div class="totals">${sale.discount?`<div><span>Subtotal</span><strong>${brl(sale.subtotal!=null?sale.subtotal:sale.total)}</strong></div><div><span>Desconto</span><strong>-${brl(sale.discount)}</strong></div>`:''}<div class="total"><span>Total</span><strong>${brl(sale.total)}</strong></div>${paymentRows}${sale.troco?`<div><span>Troco</span><strong>${brl(sale.troco)}</strong></div>`:''}</div></div><button class="finish" id="printReceipt" style="margin-top:14px">Imprimir recibo</button>`);$('printReceipt').onclick=()=>window.print()}
function initLogin(){
  if(!state.users.length){
    $('loginHint').classList.remove('hidden');
    $('loginBtn').textContent='Criar administrador';
    if(!$('loginName')){
      const nameDiv=document.createElement('div');
      nameDiv.innerHTML='<label>Seu nome</label><input id="loginName" placeholder="Ex.: Maria">';
      $('loginUser').closest('div').before(nameDiv);
    }
  }else{
    $('loginHint').classList.add('hidden');
    $('loginBtn').textContent='Entrar';
    const existingName=$('loginName');
    if(existingName)existingName.closest('div').remove();
  }
  const savedId=localStorage.getItem(SESSION_KEY);
  const savedUser=savedId?state.users.find(u=>u.id===savedId):null;
  if(savedUser){enterApp(savedUser)}else{showLogin()}
}
function showLogin(){$('loginScreen').classList.remove('hidden');$('appRoot').classList.add('hidden');$('loginUser').value='';$('loginPass').value='';$('loginError').classList.add('hidden');setTimeout(()=>$('loginUser').focus(),50)}
function enterApp(user){currentUser=user;localStorage.setItem(SESSION_KEY,user.id);$('loginScreen').classList.add('hidden');$('appRoot').classList.remove('hidden');const isAdmin=user.role==='admin';$('currentUserLabel').innerHTML=`${user.name} <span class="role-badge ${isAdmin?'admin':''}">${isAdmin?'Admin':'Operador'}</span>`;render()}
function doLogin(){const username=$('loginUser').value.trim();const password=$('loginPass').value;if(!state.users.length){const nameEl=$('loginName');const name=nameEl?nameEl.value.trim():'';if(!name||!username||!password){$('loginError').textContent='Preencha nome, usuário e senha.';$('loginError').classList.remove('hidden');return}const admin={id:'u'+Date.now(),name,username,password,role:'admin'};state.users.push(admin);save();initLogin();enterApp(admin);toast('Administrador criado. Bem-vindo(a)!');return}if(!username||!password){$('loginError').textContent='Informe usuário e senha.';$('loginError').classList.remove('hidden');return}const user=state.users.find(u=>u.username.toLowerCase()===username.toLowerCase()&&u.password===password);if(!user){$('loginError').textContent='Usuário ou senha incorretos.';$('loginError').classList.remove('hidden');return}enterApp(user)}
function logout(){currentUser=null;localStorage.removeItem(SESSION_KEY);showLogin()}
function usersModal(){const isAdmin=currentUser.role==='admin';openModal('Usuários',`<div class="form"><div><label>Nome</label><input id="un"></div><div><label>Usuário (login)</label><input id="uu"></div><div><label>Senha</label><input id="up" type="password"></div><div><label>Perfil</label><select id="ur"><option value="operador">Operador (caixa)</option><option value="admin">Administrador</option></select></div><div style="display:flex;align-items:end"><button id="addU">Adicionar usuário</button></div></div><table class="table"><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th></th></tr></thead><tbody>${state.users.map(u=>`<tr><td>${u.name}${u.fixed?' <span style="color:var(--muted);font-size:11px">(fixo)</span>':''}</td><td>${u.username}</td><td><span class="role-badge ${u.role==='admin'?'admin':''}">${u.role==='admin'?'Admin':'Operador'}</span></td><td><button class="remove" data-del-user="${u.id}" ${!isAdmin?'disabled title="Apenas administradores podem excluir"':(u.id===currentUser.id?'disabled title="Você não pode excluir seu próprio usuário"':(u.fixed?'disabled title="Usuário fixo do sistema"':''))}>Excluir</button></td></tr>`).join('')}</tbody></table>`);$('addU').onclick=()=>{const name=$('un').value.trim(),username=$('uu').value.trim(),password=$('up').value,role=$('ur').value;if(!name||!username||!password){toast('Preencha todos os campos.');return}if(state.users.some(u=>u.username.toLowerCase()===username.toLowerCase())){toast('Já existe um usuário com esse login.');return}state.users.push({id:'u'+Date.now(),name,username,password,role});save();usersModal();toast('Usuário criado.')};document.querySelectorAll('[data-del-user]').forEach(b=>b.onclick=()=>{if(b.disabled)return;if(!confirm('Excluir este usuário?'))return;state.users=state.users.filter(u=>u.id!==b.dataset.delUser);save();usersModal()})}
$('loginBtn').onclick=doLogin;$('loginPass').addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});$('logoutBtn').onclick=logout;$('openUsers').onclick=usersModal;
initLogin();
$('search').addEventListener('input',renderProducts);$('clearCart').onclick=()=>{cart=[];payment=null;discount=0;splits=[];splitMode=false;$('discountInput').value='';$('singlePayment').classList.remove('hidden');$('splitPayment').classList.add('hidden');$('toggleSplit').textContent='Dividir pagamento';renderSplitList();render();document.querySelectorAll('[data-payment]').forEach(b=>b.classList.remove('selected'))};$('useWeight').onclick=addWeight;$('connectScale').onclick=connectScale;$('cashReceived').addEventListener('input',updateChange);$('discountInput').addEventListener('input',()=>{discount=parseFloat($('discountInput').value||0);if(discount<0)discount=0;renderCart()});$('toggleSplit').onclick=toggleSplit;$('addSplit').onclick=addSplit;$('finishSale').onclick=finishSale;$('openProducts').onclick=productsModal;$('openReports').onclick=reportsModal;$('openSettings').onclick=scaleModal;$('closeModal').onclick=closeModal;$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});document.querySelectorAll('[data-payment]').forEach(b=>b.onclick=()=>{payment=b.dataset.payment;document.querySelectorAll('[data-payment]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('cashChange').classList.toggle('hidden',payment!=='Dinheiro')});
